name: tutorial-app-platform
static_sites:
- name: frontend
  github:
    repo: sciabarrado/tutorial-app-platform
    branch: main
    deploy_on_push: true
  source_dir: frontend
  build_command: npm run build
  routes:
  - path: /
services:
- name: backend
  github:
    repo: sciabarrado/tutorial-app-platform
    branch: main
    deploy_on_push: true
  run_command: node index.js
  source_dir: backend
  routes:
  - path: /api
